import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class AutomatedYellowIcon extends React.Component {
  displayName = 'AutomatedYellowIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} width="60px" height="60px" viewBox="0 0 60 60" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <defs />
      <g id="Page-1" stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd">
        <g id="Desktop-Copy-2" transform="translate(-289.000000, -737.000000)">
          <g id="1bn" transform="translate(128.000000, 585.000000)">
            <rect id="Rectangle-7" x={0} y={0} width={1024} height={381} />
            <path d="M163,154 L219,154 L219,210 L163,210 L163,154 Z" id="Path" fill="#FFF7E0" />
            <g id="Group-+-Fully-automated-+-Save-time,-stop-huma-+-Fill-2730-+-Fill-2731-+-Ultra-low-fees-+-Less-than-half-the-c-+-Fill-1659-+-Fill-1660-+-12,000+-merchants-+-Powering-payments-fo" transform="translate(42.000000, 152.000000)" fill="#5092DA">
              <g id="Group-+-Fully-automated-+-Save-time,-stop-huma">
                <g id="Group" transform="translate(119.000000, 0.000000)">
                  <path d="M2,2 L58,2 L58,58 L2,58 L2,2 Z M59,0 L1,0 C0.45,0 0,0.5 0,1 L0,59 C0,59.6 0.45,60 1,60 L59,60 C59.55,60 60,59.6 60,59 L60,1 C60,0.5 59.55,0 59,0 L59,0 Z" id="Fill-1002" />
                  <path d="M12.9,23.201 C13.09,23.4 13.34,23.5 13.61,23.5 C13.87,23.5 14.13,23.4 14.31,23.201 L26.92,10.6 C27.31,10.201 27.31,9.5 26.92,9.2 C26.53,8.8 25.9,8.8 25.51,9.2 L13.61,21.1 L9.27,16.7 C8.88,16.3 8.25,16.3 7.86,16.7 C7.47,17.1 7.47,17.701 7.86,18.1 L12.9,23.201" id="Fill-1003" />
                  <path d="M12.9,47.1 C13.1,47.3 13.35,47.4 13.61,47.4 C13.86,47.4 14.12,47.3 14.31,47.1 L26.92,34.5 C27.31,34.1 27.31,33.5 26.92,33.1 C26.53,32.701 25.9,32.701 25.51,33.1 L13.61,45 L9.27,40.7 C8.88,40.3 8.25,40.3 7.86,40.7 C7.47,41.1 7.47,41.701 7.86,42.1 L12.9,47.1" id="Fill-1004" />
                  <path d="M31.26,22.201 L51.43,22.201 C51.99,22.201 52.43,21.8 52.43,21.2 C52.43,20.701 51.99,20.201 51.43,20.201 L31.26,20.201 C30.71,20.201 30.26,20.701 30.26,21.2 C30.26,21.8 30.71,22.201 31.26,22.201" id="Fill-1005" />
                  <path d="M31.26,44 L51.43,44 C51.99,44 52.43,43.6 52.43,43 C52.43,42.5 51.99,42 51.43,42 L31.26,42 C30.71,42 30.26,42.5 30.26,43 C30.26,43.6 30.71,44 31.26,44" id="Fill-1006" />
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
    </svg>

    );
  }
}

