import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class ConnectTeamsIcon extends React.Component {
  displayName = 'ConnectTeamsIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width={62} height="54.97" viewBox="0 0 62 54.97"><title>ConnectTeams</title><circle cx="49.55" cy="12.45" r="11.45" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="49.55" cy="8.62" r="3.09" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M54.71,17.89H44.4c0-3.42,2.31-6.18,5.15-6.18S54.71,14.48,54.71,17.89Z" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="31.87" cy="43.3" r="10.67" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="31.87" cy="39.73" r="2.88" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M36.67,48.37H27.06c0-3.18,2.15-5.76,4.8-5.76S36.67,45.19,36.67,48.37Z" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="11.07" cy="20.14" r="10.07" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="11.07" cy="16.77" r="2.72" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M15.61,24.94H6.54c0-3,2-5.44,4.53-5.44S15.61,21.93,15.61,24.94Z" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><line x1="19.07" y1="29.41" x2="23.16" y2="34.31" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><line x1="36.25" y1="31.88" x2="40.93" y2={24} style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /></svg>

    );
  }
}

