import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class DevelopTestIterateIcon extends React.Component {
  displayName = 'DevelopTestIterateIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width={62} height="57.09" viewBox="0 0 62 57.09"><title>DevelopTestIterate</title><circle cx="31.43" cy="32.15" r="23.94" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2, strokeDasharray: '4,3'}} /><circle cx="30.77" cy="10.4" r="9.4" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="26.59 10.67 29.2 13.28 34.95 7.53" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="10.4" cy="40.03" r="9.4" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="6.23 40.3 8.83 42.91 14.58 37.16" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="51.6" cy="40.03" r="9.4" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="47.42 40.3 50.03 42.91 55.77 37.16" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /></svg>

    );
  }
}

