import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class DownloadPdfIcon extends React.Component {
  displayName = 'DownloadPdfIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} width="16px" height="16px" viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <defs />
      <g id="Page-1" stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd" strokeLinecap="round" stroke-linejoin="round">
        <g id="02f-i---Integrate-api-Copy" transform="translate(-297.000000, -2508.000000)" stroke="#5092DA">
          <g id="DownloadPdf" transform="translate(298.000000, 2509.000000)">
            <polyline id="Stroke-1" points="10.3829753 7.1504137 6.96064658 10.5727425 3.69787945 7.30997534" />
            <path d="M6.95999146,10.5727233 L6.96066575,2.51121644" id="Stroke-2" />
            <path d="M13.8254411,6.96066575 C13.8254411,10.7519808 10.7519616,13.8254603 6.96064658,13.8254603 C3.16933151,13.8254603 0.0958520548,10.7519808 0.0958520548,6.96066575 C0.0958520548,3.16935068 3.16933151,0.0958712329 6.96064658,0.0958712329 C10.7519616,0.0958712329 13.8254411,3.16935068 13.8254411,6.96066575 L13.8254411,6.96066575 Z" id="Stroke-3" />
          </g>
        </g>
      </g>
    </svg>

    );
  }
}

