import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class FacebookIcon extends React.Component {
  displayName = 'FacebookIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} width="8px" height="16px" viewBox="0 0 8 16" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <title>Facebook</title>
      <g stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd">
        <g transform="translate(-421.000000, -31.000000)" fill="#5092DA">
          <g transform="translate(349.000000, 29.000000)">
            <path d="M80,6.85260179 L77.2168243,6.85260179 L77.2168243,5.52536469 C77.2168243,4.90111039 77.6041735,4.7554975 77.8767525,4.7554975 L79.8252364,4.7554975 L79.8252364,2.00905726 L77.0022824,2 C74.4421259,2 73.9563091,4.04763771 73.9563091,5.35815371 L73.9563091,6.85260179 L72,6.85260179 L72,9.63945134 L73.9563091,9.63945134 L73.9563091,18 L77.2168243,18 L77.2168243,9.63945134 L79.728073,9.63945134 L80,6.85260179 L80,6.85260179 Z" id="facebook" />
          </g>
        </g>
      </g>
    </svg>

    );
  }
}

