import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class IncreaseConversionIcon extends React.Component {
  displayName = 'IncreaseConversionIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width={60} height="57.7" viewBox="0 0 60 57.7"><title>IncreaseConversion</title><polyline points="19.56 56.32 19.56 36.03 27.44 36.03 27.44 56.32" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="32.43 56.32 32.43 27.54 40.31 27.54 40.31 56.32" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="45.3 56.32 45.3 15.75 53.18 15.75 53.18 56.32" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M30.12,17.73" style={{fill: '#fff7f6', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><line x1="47.44" y1="1.58" x2="8.03" y2="32.12" style={{fill: '#fff7f6', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="6.69 56.32 6.69 46.18 14.57 46.18 14.57 56.32" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><line y1="56.7" x2={60} y2="56.7" style={{fill: '#fff7f6', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="40.54 1 47.54 1 47.54 8" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /></svg>

    );
  }
}

