import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class LinkedinIcon extends React.Component {
  displayName = 'LinkedinIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} width="18px" height="18px" viewBox="0 0 18 18" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <title>Linkedin</title>
      <g stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd">
        <g transform="translate(-349.000000, -29.000000)" fill="#5092DA">
          <g transform="translate(349.000000, 29.000000)">
            <path d="M12.0077044,9.85643191 C11.0617777,9.85643191 10.2956199,10.6671694 10.2956199,11.6661137 L10.2956199,18 L6.01540876,18 C6.01540876,18 6.06591525,7.14190921 6.01540876,6.23706832 L10.2956199,6.23706832 L10.2956199,7.58075705 C10.2956199,7.58075705 11.6207733,6.27507163 13.6675703,6.27507163 C16.2023113,6.27507163 18,8.21414568 18,11.9791887 L18,18 L13.7197888,18 L13.7197888,11.6661137 C13.7197888,10.6671694 12.953631,9.85643191 12.0077044,9.85643191 L12.0077044,9.85643191 Z M2.1546583,4.42738652 L2.12983307,4.42738652 C0.83635326,4.42738652 0,3.35786458 0,2.18247625 C0,0.979942693 0.862034527,0 2.18033956,0 C3.49950064,0 4.31017264,1.01161212 4.3358539,2.21414568 C4.3358539,3.39043885 3.49950064,4.42738652 2.1546583,4.42738652 L2.1546583,4.42738652 Z M4.3033243,18 L0.0231131402,18 L0.0231131402,6.23706832 L4.3033243,6.23706832 L4.3033243,18 Z" id="linkedin" />
          </g>
        </g>
      </g>
    </svg>

    );
  }
}

