import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class NewToDdIcon extends React.Component {
  displayName = 'NewToDdIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} width="53px" height="55px" viewBox="0 0 53 55" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <title>new</title>
      <desc>Created with Sketch.</desc>
      <defs />
      <g id="Page-1" stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd">
        <g id="Landing-Page---Final" transform="translate(-616.000000, -477.000000)" stroke="#5092DA">
          <g id="Header" transform="translate(-3.000000, 59.000000)">
            <g id="How-Can-we-Help-Modules" transform="translate(173.000000, 381.000000)">
              <g id="New-to-DD" transform="translate(319.000000, 1.000000)">
                <g id="Deal-Copy" transform="translate(18.000000, 36.117936)">
                  <g id="new" transform="translate(110.322034, 0.000000)">
                    <g id="Page-1" transform="translate(0.000000, 0.882064)">
                      <path d="M4.90210328,36.6891492 L4.90210328,21.5839525" id="Stroke-1" strokeWidth="1.3" />
                      <path d="M3.01393279,36.6891492 L12.4547852,36.6891492" id="Stroke-2" strokeWidth="1.3" />
                      <g id="Group-7" transform="translate(0.000000, 40.308644)" strokeWidth="1.5">
                        <path d="M0.627718033,3.93327049 L24.4539148,3.93327049" id="Stroke-3" />
                        <path d="M0.627718033,0.156929508 L24.4539148,0.156929508" id="Stroke-5" />
                      </g>
                      <path d="M3.01393279,21.5837016 L12.4547852,21.5837016" id="Stroke-8" strokeWidth="1.3" />
                      <path d="M16.6254148,36.6891492 L26.0662672,36.6891492" id="Stroke-9" strokeWidth="1.3" />
                      <path d="M16.6254148,21.5837016 L26.0662672,21.5837016" id="Stroke-10" strokeWidth="1.3" />
                      <path d="M10.5666148,36.6891492 L10.5666148,21.5839525" id="Stroke-11" strokeWidth="1.3" />
                      <path d="M18.5135852,36.6891492 L18.5135852,21.5839525" id="Stroke-12" strokeWidth="1.3" />
                      <path d="M24.1781803,36.6891492 L24.1781803,21.5839525" id="Stroke-13" strokeWidth="1.3" />
                      <path d="M30.734941,21.5837016 L40.1757934,21.5837016" id="Stroke-14" strokeWidth="1.3" />
                      <path d="M32.6231115,30.6530902 L32.6231115,21.5834508" id="Stroke-15" strokeWidth="1.3" />
                      <path d="M38.287623,28.2386164 L38.287623,21.5835344" id="Stroke-16" strokeWidth="1.3" />
                      <g id="Group-25" transform="translate(0.836066, 0.177497)" strokeWidth="1.5">
                        <polygon id="Stroke-17" points="0.073657377 17.6298639 41.1721328 17.6298639 20.6784934 0.635995082" />
                        <path d="M38.2897967,30.3715869 C44.5059443,30.3715869 49.5449115,35.4105541 49.5449115,41.6267016 C49.5449115,47.8420131 44.5059443,52.8809803 38.2897967,52.8809803 C32.0736492,52.8809803 27.034682,47.8420131 27.034682,41.6267016 C27.034682,35.4105541 32.0736492,30.3715869 38.2897967,30.3715869 Z" id="Stroke-19" />
                        <path d="M38.206441,47.8982803 L38.2607852,36.0127721" id="Stroke-21" />
                        <path d="M32.3176131,41.9282705 L44.2031213,41.9826148" id="Stroke-23" />
                      </g>
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
    </svg>

    );
  }
}

