import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class NoSetUpFeesIcon extends React.Component {
  displayName = 'NoSetUpFeesIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width="35.12" height="40.26" viewBox="0 0 35.12 40.26"><title>NoSetUpFees</title><polyline points="16.65 35.05 0.75 35.05 0.75 0.75 17.16 0.75 26.11 9.7 26.11 21.13" style={{fill: '#fff7f6', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><polyline points="17.16 0.75 17.16 9.7 26.11 9.7" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="10.67" y1="14.66" x2="20.14" y2="14.66" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="10.67" y1="20.63" x2="20.14" y2="20.63" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="10.67" y1="26.59" x2="16.66" y2="26.59" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><circle cx="26.29" cy="31.43" r="8.08" style={{fill: '#fff7f6', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><circle cx="6.48" cy="15.01" r="1.13" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><circle cx="6.48" cy="20.77" r="1.13" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><circle cx="6.48" cy="26.53" r="1.13" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="29.17" y1="28.3" x2="23.41" y2="34.06" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="29.17" y1="34.06" x2="23.41" y2="28.3" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /></svg>

    );
  }
}

