import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class PredictablePricingIcon extends React.Component {
  displayName = 'PredictablePricingIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width="29.5" height="28.62" viewBox="0 0 29.5 28.62"><title>PredictablePricing</title><circle cx="11.52" cy="11.52" r="10.77" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><path d="M10.88,4.28a7.8,7.8,0,0,1,7.8,7.8" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="19.62" y1="18.55" x2="28.97" y2="28.1" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /></svg>

    );
  }
}

