import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class ReduceChurnIcon extends React.Component {
  displayName = 'ReduceChurnIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width="53.11" height={62} viewBox="0 0 53.11 62"><title>ReduceChrn</title><circle cx="26.58" cy="31.01" r="23.88" style={{fill: '#f2faf2'}} /><path d="M19.09,55.39a25.56,25.56,0,0,1,7.47-50" style={{fill: 'none', stroke: '#5092da', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2}} /><path d="M32.75,6.14a25.56,25.56,0,0,1-6.2,50.36" style={{fill: 'none', stroke: '#5092da', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2}} /><polyline points="22.39 1 26.91 5.53 21.96 10.46" style={{fill: 'none', stroke: '#5092da', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2}} /><polyline points="30.72 61 26.15 56.52 31.04 51.53" style={{fill: 'none', stroke: '#5092da', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2}} /><line x1="20.18" y1="31.24" x2="29.61" y2="31.24" style={{fill: 'none', stroke: '#5092da', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2}} /><path d="M33,25.66a4.72,4.72,0,1,0-9.43,0V36.38a4.29,4.29,0,0,1-4.29,4.29H33" style={{fill: 'none', stroke: '#5092da', strokeLinecap: 'round', strokeLinejoin: 'round', strokeWidth: 2}} /></svg>

    );
  }
}

