import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class ScalablePlansIcon extends React.Component {
  displayName = 'ScalablePlansIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width="29.97" height="35.42" viewBox="0 0 29.97 35.42"><title>ScalablePlans</title><line y1="34.67" x2="29.56" y2="34.67" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><polyline points="1.43 32.11 1.43 25.21 7.9 25.21 7.9 32.11" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><polyline points="12.18 32.11 12.18 18.31 18.66 18.31 18.66 32.11" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><polyline points="22.75 32.11 22.75 11.42 29.22 11.42 29.22 32.11" style={{fill: '#f2f7fd', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><ellipse cx="25.99" cy="2.85" rx="2.18" ry="2.1" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><ellipse cx="15.59" cy="11.74" rx="2.18" ry="2.1" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><ellipse cx="4.35" cy="19.36" rx="2.18" ry="2.1" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="6.76" y1="18.05" x2="14.32" y2="12.82" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /><line x1="24.69" y1="4.21" x2="16.83" y2="10.72" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: '1.5px'}} /></svg>

    );
  }
}

