import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class SecurityFillIcon extends React.Component {
  displayName = 'SecurityFillIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      {/*?xml version="1.0" encoding="UTF-8" standalone="no"?*/}
    <svg {...this.props} width="43px" height="60px" viewBox="0 0 43 60" version="1.1" :xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      {/* Generator: Sketch 3.6.1 (26313) - http://www.bohemiancoding.com/sketch */}
      <title>security-fill-icon</title>
      <desc>Created with Sketch.</desc>
      <defs />
      <g id="Page-1" stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd">
        <g id="Desktop" transform="translate(-457.000000, -322.000000)">
          <g id="security-fill-icon" transform="translate(457.000000, 322.000000)">
            <path d="M2.0046676,58 L40.0046676,58 L40.0046676,26 L2.0046676,26 L2.0046676,58 Z" id="Fill-3" fill="#F2FAF2" />
            <path d="M36.0046676,24 L36.0046676,16 C36.0046676,8.273 29.9776676,0 21.0046676,0 C12.0316676,0 6.0046676,8.273 6.0046676,16 L6.0046676,24 L0.00466759833,24 L0.00466759833,60 L42.0046676,60 L42.0046676,24 L36.0046676,24 Z M2.0046676,58 L40.0046676,58 L40.0046676,26 L2.0046676,26 L2.0046676,58 Z M20.0046676,39.7217 L20.0046676,46.5667 C20.0046676,47.1187 20.4526676,47.5667 21.0046676,47.5667 C21.5566676,47.5667 22.0046676,47.1187 22.0046676,46.5667 L22.0046676,39.7217 C22.5996676,39.3747 23.0046676,38.7367 23.0046676,37.9997 C23.0046676,36.8977 22.1076676,35.9997 21.0046676,35.9997 C19.9016676,35.9997 19.0046676,36.8977 19.0046676,37.9997 C19.0046676,38.7367 19.4096676,39.3747 20.0046676,39.7217 Z M8.0046676,16 C8.0046676,9.239 13.2286676,2 21.0046676,2 C28.7806676,2 34.0046676,9.239 34.0046676,16 L34.0046676,24 L8.0046676,24 L8.0046676,16 Z" id="Combined-Shape" fill="#5092DA" />
          </g>
        </g>
      </g>
    </svg>

    );
  }
}

