import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class SimpleSetupIcon extends React.Component {
  displayName = 'SimpleSetupIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width="62.37" height="57.82" viewBox="0 0 62.37 57.82"><title>SimpleSetup</title><path d="M26.05,45.54H6.57A5.57,5.57,0,0,1,1,40V6.57A5.57,5.57,0,0,1,6.57,1H51.11a5.57,5.57,0,0,1,5.57,5.57V27.44" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><line x1={1} y1="12.13" x2="56.67" y2="12.13" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M9.35,5.18a1.39,1.39,0,1,0,1.39,1.39A1.39,1.39,0,0,0,9.35,5.18Z" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M14.92,5.18a1.39,1.39,0,1,0,1.39,1.39,1.39,1.39,0,0,0-1.39-1.39Z" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M20.49,5.18a1.39,1.39,0,1,0,1.39,1.39,1.39,1.39,0,0,0-1.39-1.39Z" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><path d="M58,37.1l3-1.72-4.18-7.23-3,1.73a13.89,13.89,0,0,0-5.19-3V23.41H40.27V26.9a13.92,13.92,0,0,0-5.19,3l-3-1.73-4.18,7.23,3,1.72a13.23,13.23,0,0,0,0,6l-3,1.72,4.18,7.23,3-1.73a13.88,13.88,0,0,0,5.19,3v3.49h8.35V53.33a13.92,13.92,0,0,0,5.19-3l3,1.73L61,44.85l-3-1.72A13.23,13.23,0,0,0,58,37.1Z" style={{fill: '#f2faf2', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><circle cx="44.45" cy="40.12" r="5.57" style={{fill: '#fff', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /></svg>

    );
  }
}

