import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class SliderArrowIcon extends React.Component {
  displayName = 'SliderArrowIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} width="18px" height="30px" viewBox="0 0 18 30" version="1.1" xmlns="http://www.w3.org/2000/svg">
      <defs />
      <g id="Page-1" stroke="none" strokeWidth={1} fill="none" fill-rule="evenodd">
        <g id="02b---DD-funnel" transform="translate(-1184.000000, -2091.000000)" fill="#000000">
          <polygon id="slider-arrow" points="1184 2094.18198 1187.15013 2091 1202 2106 1187.15013 2121 1184 2117.81802 1195.69973 2106" />
        </g>
      </g>
    </svg>

    );
  }
}
