import React from 'react';
// Warning!
// Autogenerated - do not edit.
// Edit SVG icons in public/images/icons and run: ./script/generators/render-icons
export default class SpeakLanguageIcon extends React.Component {
  displayName = 'SpeakLanguageIcon'

  static propTypes = {
    className: React.PropTypes.string,
  };

  render() {
    return (
      <svg {...this.props} xmlns="http://www.w3.org/2000/svg" width="45.21" height="54.77" viewBox="0 0 45.21 54.77"><title>SpeakLanguage</title><polygon points="29.13 53.77 1 53.77 1 1 31.64 1 44.21 13.56 44.21 23.62 44.21 53.77 29.13 53.77" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="31.64 1 31.64 13.56 44.21 13.56" style={{fill: 'none', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="18.57 23.11 11.03 30.64 18.57 38.18" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /><polyline points="26.11 23.11 33.64 30.64 26.11 38.18" style={{fill: '#fefaea', stroke: '#5092da', strokeMiterlimit: 10, strokeWidth: 2}} /></svg>

    );
  }
}

